### ISSUE TITLE
Translate the demo for French presentations

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#12]
We have to translate The Following bodies of labels ( sorted by priority ) 
Please don't delete the empty lines of the translations sheets, they are useful for us

- [x] App translations
document : https://docs.google.com/spreadsheets/d/1NL8dIIE1bdeUAAH_yDZKEv7C4muHqjv4X_Z6pGLW8HM/edit#gid=0
- [x] patient self assessment text messages 
document : https://docs.google.com/spreadsheets/d/1NL8dIIE1bdeUAAH_yDZKEv7C4muHqjv4X_Z6pGLW8HM/edit#gid=437136341
- [x] Covid RDT forms and tasks 
document : https://docs.google.com/spreadsheets/d/1NL8dIIE1bdeUAAH_yDZKEv7C4muHqjv4X_Z6pGLW8HM/edit#gid=1452029111
- [x] Nepal Airport PoE forms 
document : https://docs.google.com/spreadsheets/d/1NL8dIIE1bdeUAAH_yDZKEv7C4muHqjv4X_Z6pGLW8HM/edit#gid=1593192689
- [x] Patient creation form 
document : https://docs.google.com/spreadsheets/d/1NL8dIIE1bdeUAAH_yDZKEv7C4muHqjv4X_Z6pGLW8HM/edit#gid=1496678736

**Comment by fatousylla** [comment]
@senseibara The attached documents have been translated. It is not possible to put a checkmark in front of the items.

**Comment by senseibara** [comment]
@fatousylla thanks, i updated the remaining translations you can find two new columns in the sheet, please let loukman know

**Comment by fatousylla** [comment]
Ok @senseibara

**Comment by fatousylla** [comment]
@senseibara The 2 added forms have been translated.
