### ISSUE TITLE
Production instance for Covid Response (cht-covid)

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#21]
We will need another instance for Covid response use cases that would only be used for live demos and partner facing exchanges. 

Instance Name: cht-covid.app.medicmobile.org
Latest release of CHT + default config.

As we have some work and demos to come on monday (30th march), this is an urgent request. 
@medic/site-reliability-engineering

**Comment by nomulex** [comment]
Created on `v3.8` credentials stored in 1password. reach out in case of any issues arising.
