### ISSUE TITLE
Alignment with configuration repository guidelines

### ISSUE THREAD

**Issue by eljhkrr** [medic/config-covid#22]
The App Services Team has come up with a configuration repository framework that will streamline project configuration work.

Information on this framework can be found [here.](https://github.com/medic/app-services-team/blob/master/repositories.md)

This issue is for tracking implementation of the directives specified and can be closed once everything has been set up correctly.

https://github.com/medic/app-services-team/issues/8

**Comment by kennsippell** [comment]
@eljhkrr can you do this one please?

**Comment by eljhkrr** [comment]
Done
