### ISSUE TITLE
Configure a trace request form

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#26]
Pre-requisite : We should add an option “Patient zero” on the person creation/edit form.

Create a action form called : Trace Request form, 
id : `trace_request`
context : only available to person contact that have the role `patient_zero`
Purpose : This is the form that is used to enter tracing contacts c1..N for a patient zero . 
 
From the submission of that form, we generate new patient profiles for each c1..N in the appropriate Tracer Area.
 
Inside the Trace Request form we should include : 

**1/ Fields for information about the Patient 0 (Update on person create/edit form )**

Outbreak Case ID
Surname
Other Names 
phone
Address
Town
 
**2/ Contacts that have to be traced and information**

A Repeat option to add as much contacts as needed 
For every contact in that repeat we should have these informations : 
 
Surname 
Other names
Sex
Age in years
Phone No
Flight details (if relevant)
Where the contact took place
Address
Town
Village name
Chief of village ( name and phone )
Church name 
Tracer area : this would be a db search field to assign the tracer area that exist within the app and which would be the parent of the contact 
 

 
Note : c1..N should be linked to P0 , we could add the patient_uuid  in both the contacts profile and the trace request form

**Comment by michaelkohn** [comment]
Two things: 
---
(1) I don't think we need all the fields mentioned in... 
> 1/ Fields for information about the Patient 0

...because they should be on the person-create/edit form, right? 

---
(2) It may be implied, but I want to make sure the fields mentioned in 
>2/ Contacts that have to be traced and information

...are carried over to the newly created contact's profile. All of this information is going to also be displayed on the Trace f/u form.

**Comment by binokaryg** [comment]
Pull request created #41
