### ISSUE TITLE
Send messages to tracer and to patient when a patient is enrolled by the data input

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#27]
1. Make an outbound config to send to the tracer a sms via Text-it ( an example is available in the existing config );

The outbound task is triggered every time a contact is created from the `trace_request` form.

Among the information we send, we have to make sure to include the patient_name and tracer_phone for any contact listed. 

2. Make an outbound config to send to Textit the patient_name, patient_phone and tracer_name for any contact listed, we filter the docs without a phone number in the relevant key

**Comment by michaelkohn** [comment]
> Make an outbound config to send to Textit the patient_name, patient_phone and tracer_name for any contact listed

The patient_phone field will not be a required field so this should only process those who have a phone number specified.

**Comment by senseibara** [comment]
It will be a required field but we filter the docs without a phone number in the `relevant` key, adding that...

**Comment by senseibara** [comment]
https://github.com/medic/config-covid/pull/54
