### ISSUE TITLE
Configure a task that is generated for every new contact that needs to be traced

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#28]
Create a task for the Tracer for every new contact created in his area that comes from the Trace Request form. 

id : `trace_follow_up`
name : Trace follow-up
Start date : The reported date of the trace request form or the contact 
Due date : the same day as start date 
End date : One month later 
 
Content

Print the following fields from the patient doc : 

Surname
Other names
Sex
Age in years
Phone No
Flight details (if relevant)
Where the contact took place
Address
Town
Village name
Chief of village ( name and phone )
Church name
Patient zero name

Q1. Was the trace attempt successful or do you want to stop tracing this contact ? ( select_one )
1. Contacted
2. Couldn’t contact but will try again
3. Stop tracing this contact 

Q2. Does the patient have covid symptoms ? (Yes/No ) 
 
if Q1 = contacted > resolve the task 
if Q1 = couldn't contact > do not resolve the task
if Q1 = stop tracing > Ask to provide more details about the investigation then resolve the task. 

Include a `needs_signoff` that would become true if the stop tracing option is selected. The upper level i.e. the Data entry should receive that form

**Comment by michaelkohn** [comment]
This form is intended to be used by the Tracer to do the actual tracing so they should have all the relevant information available to them to do the tracing. So before asking Q1 and Q2, we should display all the information mentioned in the second section of https://github.com/medic/config-covid/issues/26

```
Surname
Other names
Sex
Age in years
Phone No
Flight details (if relevant)
Where the contact took place
Address
Town
Village name
Chief of village ( name and phone )
Church name
```

...and ideally (if possible), this contact's patient zero name.

**Comment by senseibara** [comment]
updated

**Comment by binokaryg** [comment]
It depends on #26, so working on it side-by-side.

**Comment by senseibara** [comment]
i was also suspecting it might be tricky without that base, thanks for taking both 👌🏽

**Comment by binokaryg** [comment]
Pull request created #41
