### ISSUE TITLE
Create a follow-up task when the RDT result is Positive

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#3]
**Source Form** : covid_rdt
**Task** : Covid Follow up 
Time window : The task will be due the next day after the follow up but appears 1 day before
**Content** : The task come after the RDT is positive, considering the patient will be referred to a facility to do another test, The task should ask if you called the patient to have news on his situation.

cc @michaelkohn

**Comment by kennsippell** [comment]
What should the task do when you click it?
I'm going to commit this to https://github.com/medic/config-covid?

**Comment by senseibara** [comment]
Yes @kennsippell as a pull request. 
The task come after the RDT is positive, considering the patient will be referred to a facility to do another test, The task should if you called the patient to have news on his situation.
