### ISSUE TITLE
Configure a JSON form "quarantine Followup" That is generated to capture patient self assessment response 

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#30]
id: quarantine_follow_up
name 'Quarantine follow up'
fields : > symptoms_check

When the patient provides an answer in this workflow : 
https://github.com/medic/config-covid/issues/29

Everytime a record should be created in the CHT with the response of the patient ( 1 or 2 )

**Comment by ashish-medic** [comment]
@senseibara don't we need `patient_id` in fields.

**Comment by senseibara** [comment]
hey @ashish-medic , yes we will need it, you can check on app-settings forms `PHONE_VERIFICATION` or `COVID_SYMPTOMS` to see some examples (if not already seen)

**Comment by michaelkohn** [comment]
I think we should rename the `symptoms_check` field to `new_symptoms_reported`.

Also, what should I provide (from RapidPro) as a response.... my preference would probably be true/false.
