### ISSUE TITLE
Replicate C-EBS code on Cht-covid instance

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#33]
This will need this to be done first , https://github.com/medic/medic-projects/issues/7331, 
XLS :https://docs.google.com/spreadsheets/d/1rmEPtT5_9oEXe7qyf_zMsrpz1z8aU4xn6vtDlsUkQ2g/edit#gid=697089460

**Comment by benkags** [comment]
@senseibara C-EBS as it exists includes 7 other signals. The COVID-19 one is the 8th. Do we want all of the other signals in this demo instance?

**Comment by senseibara** [comment]
yes you can just add them as it is for now, and i'll see with the squad wether we keep those, or change them to have only covid specific signals.
