### ISSUE TITLE
C-EBS : Determine which fields to include on the Signal Verification and Case Investigation forms

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#35]
For the C-EBS workflow, we were able to leverage forms from an existing EBS workflow which uses Medic Collect. We are able to convert them to CHT app forms but we need to review the actual content on the forms and adjust them to COVID specific signal reporting. This will mostly require us to remove fields from the EBS workflow.

The original Medic Collect forms can be found [here](https://github.com/medic/medic-projects/tree/master/cdc-mohke-dsru/forms/collect).

 Below is some guidance as to what some of the key datapoints we'd want to capture on the Signal Verification (CHA) and Case Investigation (Sub District Investigators) reports.
![Screen Shot 2020-04-02 at 3 15 05 PM](https://user-images.githubusercontent.com/10096985/78292394-f5a07f80-74f4-11ea-929b-431185dcc14c.png)

**Comment by senseibara** [comment]
should we consider this done now @michaelkohn @katanu

**Comment by katanu** [comment]
yes @senseibara
