### ISSUE TITLE
Iterate on C-EBS after first feedbacks and provided XLS

### ISSUE THREAD

**Issue by senseibara** [medic/config-covid#39]
XLS : https://docs.google.com/spreadsheets/d/1rmEPtT5_9oEXe7qyf_zMsrpz1z8aU4xn6vtDlsUkQ2g/edit#gid=670805354
Feedback : https://docs.google.com/document/d/1K3zfI668IQLdymRh1jHKU7OqtG7rUDtIZtXxGmmzRc8/edit?disco=AAAAJS0Pxgk&ts=5e89a312&usp=slack

---
### **CHW SMS Response**
_Current Message_
`Thank you {CHW Name} for reporting a public health signal. Signal unique ID is {Signal Unique ID}. {Supervisor Name} will contact you soon.`

_Replace with_
`Thank you {CHW Name} for reporting a COVID-19 signal. The Signal ID is {Signal Unique ID}. {Supervisor Name} will contact you soon.`

### **Supervisor SMS Response**
_Current Message_
`{CHW Name} ({CHW Phone}) has reported a COVID-19 related signal. Signal Unique ID is {Signal Unique ID}. Log in to the CHT App to triage and confirm the signal.`

_Replace with_
`{CHW Name} ({CHW Phone}) has reported a COVID-19 signal. The Signal  ID is {Signal Unique ID}. Log in to the CHT App to verify the signal.
`

**Comment by michaelkohn** [comment]
Here are the updates to the `cha_signal_verification` form. 

- All updates are indicated in Yellow
- Updates were made on the `survey` AND `choices` tab
- On the survey tab, updates were made to `label::en`, `hint::en`, and `constraint`
- On the `survey` tab, one row should be removed
- On the `choices` tab, two rows should be added

[cha_signal_verification (2020-04-07.1).xlsx](https://github.com/medic/config-covid/files/4445199/cha_signal_verification.2020-04-07.1.xlsx)

**Comment by michaelkohn** [comment]
Here are the updates to the `scdsc_investigation` form. 

- All updates are indicated in Yellow
- Updates were made on the `survey` AND `choices` tab
- On the `survey` tab, updates were made to `label::en` and `hint::en`
- On the `survey` tab, two rows need to change `type`
- On the `choices` tab, 11 rows should be added and one should have a label updated

[scdsc_investigation (2020-04-07.1).xlsx](https://github.com/medic/config-covid/files/4445511/scdsc_investigation.2020-04-07.1.xlsx)

**Comment by senseibara** [comment]
addressed
