### ISSUE TITLE
Create outbound task to trigger self quarantine messages in TextIt

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#42]
Create `outbound` task that will add a contact to a Group in TextIt and also update a field on the Contact.

The documentation on TextIt’s API can found [here](https://textit.in/api/v2/contacts).  

You will need the phone number from the patient in the CHT. 

We need to update two things on the contact in TextIt.  It’s OK if the contact doesn’t exist in TextIt just yet, I believe the POST will create it if it doesn’t already exist.

The field on the TextIt contact that we need to update is called `self_quarantine_enrollment` and you should set it to todays date. In my tests, TextIt can handle the date format like this: `dd-mm-yyyy hh:mm` so `25-03-2020 23:25` would be valid.

We also need to add this contact to a “Group” in TextIt.  The UUID of the Group in TextIt is `21052849-d169-4d70-a906-135071b27da0`. 

So if you were needing to do this to the contact with a phone number of +1317555121212, I think the payload would look something like this

```
POST /api/v2/contacts.json?urn=tel%3A%2B1317555121212
{
  "groups": [
    {
      "uuid": "21052849-d169-4d70-a906-135071b27da0"
    }
  ],
  "fields": {
    "self_quarantine_enrollment": "25-03-2020 23:25"
  }
}
```

**Comment by ashish-medic** [comment]
I am trying to put together `outbound` any pointer or example of something like this. 
Right now I am trying to figure it out 
```{
  "relevant_to": "doc.type === 'data_record' && doc.form === '?'"
}```
cc @senseibara @michaelkohn

**Comment by senseibara** [comment]
this is the task that will put the contact in the quarantine group if we do not find any symptoms https://github.com/medic/config-covid/projects/1 , so would be something like  

```"relevant_to": "doc.type === 'data_record' && doc.form === 'covid_trace_follow_up' && doc.form.trace.symptom === 'yes' "```

You could also reach out to @binokaryg who can confirm these are the fields you need to check on.

**Comment by ashish-medic** [comment]
@senseibara thanks I will reach out to @binokaryg for further information.

**Comment by binokaryg** [comment]
This should do it @ashish-medic:
```
doc.type === 'data_record' && 
doc.form === 'covid_trace_follow_up' &&
doc.fields.trace.symptom === 'no' 
```

**Comment by ashish-medic** [comment]
Here is what I have come with for the outbound part. 
But, I have a followup question in path section as we have to do `/api/v2/contacts.json?urn=tel%3A%2B1317555121212` does this  `"path": "['/api/v2/contacts.json?urn=tel' + doc.phone] "` translate what we need in as requirement suggest .Do we have any available instance to test it out. @senseibara 
```
    "textit-message": {
      "relevant_to": "doc.type === 'data_record' && doc.tasks && doc.form === 'covid_trace_follow_up' && doc.fields.trace.symptom === 'no'"",
      "destination": {
        "base_url": "https://textit.in",
        "auth": {
          "type": "header",
          "name": "Authorization",
          "value_key": "textit.in"
        },
        "path": "['/api/v2/contacts.json?urn=tel' + doc.phone] "
      },
      "mapping": {
        "groups": {
          "expr": "'21052849-d169-4d70-a906-135071b27da0'"
        },
        "extra.self_quarantine_enrollment": {
          "expr": "new Date(doc.reported_date).getDate()+'-'+ (new Date(doc.reported_date).getMonth()+1) +'-' + new Date(doc.reported_date).getFullYear()+ " " +  new Date(doc.reported_date).getHours() + ":" +  new Date(doc.reported_date).getMinutes()"
          "optional": false
        }
      }
    }
```

**Comment by senseibara** [comment]
hi @ashish-medic , you are trying to update a contact ? if yes i think for the path it should be more like 
```
"path": "/api/v2/contacts.json"
      },
      "mapping": {
        "groups": {
          "expr": "ID"
        },
        "urns": {
          "expr": "[ 'tel:' + doc.phone ]",
          "optional": false
        }, ```

To test it out you can POST it by using curl or postman, if you do ping me so we can check on textit side   :

**Comment by ashish-medic** [comment]
Yes, as per the description by @michaelkohn and document https://textit.in/api/v2/contacts we can see the example in `Updating Contacts` and we need to POST /api/v2/contacts.json?urn=tel%3A%2B1317555121212 and update doc.report to @fileds.self_quarantine_enrollment of Contact Fields. 
I did tried to update using Postman but no luck there.
