### ISSUE TITLE
patient screening form fails to build

### ISSUE THREAD

**Issue by SCdF** [medic/config-covid#65]
To reproduce:
 - Latest medic-conf on master (for me this is called `medic-conf-local`
 - Run the full suite of medic conf actions: `medic-conf-local --url=blah`

What I'd expect: everything works, converts and uploads
What actually happens: I get an error in xls2xform-medic:
![image](https://user-images.githubusercontent.com/583851/80498694-f4336d00-8963-11ea-9d70-dc56cfca2673.png)

**Comment by senseibara** [comment]
hey @SCdF if you are working on this you can use this branch that is most up to date, https://github.com/medic/config-covid/tree/covid_refinements ( the config pushed in the instance is there)

**Comment by senseibara** [comment]
Just deleted that form on that branch. There is also latest versions of all other forms in there

**Comment by SCdF** [comment]
Thanks! I'm just trying to reproduce something locally that has been raised and I hear this is the config to look at. Apologies if master is not meant to be stable, not sure what the flow on this repo is but I thought I'd raise it anyway.

I've run that branch and the whole thing passes :+1:

**Comment by SCdF** [comment]
Fixed by the `covid-refinements` branch

**Comment by kennsippell** [comment]
@senseibara What is the covid-refinements branch? Are we planning to merge it to master?

**Comment by senseibara** [comment]
@kennsippell it was a pull request that was containing a bunch of fixes and cleaning on the covid workflows. It was approved and merged to master last week.
