### ISSUE TITLE
Create CHT app remote on-boarding demo

### ISSUE THREAD

**Issue by IreneAchola** [medic/config-covid#69]

**Comment by kennsippell** [comment]
Hey @IreneAchola Is this the demo you were working on via this ticket? https://youtu.be/-24pWKckXMk Can this issue be closed?

**Comment by IreneAchola** [comment]
Yes, it's the one.
Closing as was completed.

**Comment by IreneAchola** [comment]
Add two covid education modules to the instance and create new demo chw accounts for squad members.

**Comment by IreneAchola** [comment]
Closing as complete.

**Comment by IreneAchola** [comment]
Create Module 1 for demo as documented [here](https://docs.google.com/spreadsheets/d/1zEG0LesfARZXzWKUx47M2xiV6S7KlaY6_foTCQCYnc0/edit#gid=0)

**Comment by derickl** [comment]
Is this still open @IreneAchola ?

**Comment by IreneAchola** [comment]
Closing as complete.
