### ISSUE TITLE
Update PostgreSQL roles to give volunteers access to all assets created on cht_covid_dev

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#76]
Volunteers accessing `cht_covid_dev` were assigned `{no_delete,superset_dev_db}` roles in PostgreSQL when SRE set them up.  When we create views in PostgreSQL, they are owned by `full_access`.

Working with Paul today, he wasn't able to access `ebsview_xxxx` until I ran:

`GRANT SELECT ON ebsview_signal_verification TO paulv;`

Please set up our PostgreSQL roles on `cht_covid_dev` so that all volunteers have access to run SELECT on all newly created assets on this database.

**Comment by yrimal** [comment]
Let's add this to the end of each objects created for now. 

```sql
GRANT SELECT ON [OBJECT] TO superset_dev_db 
```
