### ISSUE TITLE
Create widget in Superset for displaying cumulative number of EBS signals reported 

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#78]
This widget can just be a label and a number, we'll refine the design as things start to take shape.

### **Label**
`# of EBS signals reported`

### **Calculation**
This is just a count of `ebsview_signal_report` records.

<img width="490" alt="Screen Shot 2020-05-19 at 11 36 10 PM" src="https://user-images.githubusercontent.com/10096985/82402094-95748700-9a29-11ea-993e-79fce99cd86f.png">

**Comment by tsengtammy** [comment]
Done here: [link](https://superset.dev.medicmobile.org/superset/explore/?form_data=%7B%22datasource%22%3A%2211__table%22%2C%22viz_type%22%3A%22big_number_total%22%2C%22slice_id%22%3A43%2C%22url_params%22%3A%7B%7D%2C%22time_range_endpoints%22%3A%5B%22inclusive%22%2C%22exclusive%22%5D%2C%22granularity_sqla%22%3A%22reported%22%2C%22time_range%22%3A%22No+filter%22%2C%22metric%22%3A%22count%22%2C%22adhoc_filters%22%3A%5B%5D%2C%22y_axis_format%22%3A%22SMART_NUMBER%22%2C%22header_font_size%22%3A0.3%2C%22subheader_font_size%22%3A0.125%7D)

**Comment by michaelkohn** [comment]
Looks good! We'll tweak the size and arrangement when add this to a dashboard.
