### ISSUE TITLE
Create the EBS "Coverage" widget in Superset

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#79]
Create a line chart whose

0. **Title** is "Coverage"
1. **x-axis** is a timeframe, default being "day".  
2. **y-axis** is the number of signals
3. **Reported** (EBS02) Total number of ebsview_signal_report for the timeframe, using the `reported` date
4. **Verified** (EBS03) Total number of ebsview_signal_verification reports, using the `reported` date 
5. **Investigated** (EBS06) Total number of ebsview_signal_investigation reports, using the `reported` date

More detail about the calculations can be found [here](https://docs.google.com/spreadsheets/d/1LZt789yq_1jddG0JfccFPqnXAfzirCnzIItOy7Ovaro/edit#gid=1400309261).

<img width="487" alt="Screen Shot 2020-05-19 at 11 23 48 PM" src="https://user-images.githubusercontent.com/10096985/82401464-da97b980-9a27-11ea-81ce-975402b3c467.png">

**Comment by Pall-v** [comment]
May need to review best practices for dealing with multiple data sources in Superset.  I created some new queries withing Superset to complete this one.

**Comment by Pall-v** [comment]
updated chart to use `superset_signal_view`
