### ISSUE TITLE
Create EBS widget in superset for % of investigations with a lab sample

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#80]
This widget can just be a label and a number, we'll refine the design as things start to take shape.

### **Label**
`% with Lab samples collected`

#### **Numerator**
Count of `ebsview_signal_investigation` reports where `signal_investigated = 'yes' AND lab_samples = 'yes'`

#### **Denominator**
Count of `ebsview_signal_investigation` reports where `signal_investigated = 'yes'`

### Example
<img width="489" alt="Screen Shot 2020-05-20 at 12 13 11 AM" src="https://user-images.githubusercontent.com/10096985/82404214-b5f31000-9a2e-11ea-9790-e5977367f3d1.png">

**Comment by Pall-v** [comment]
@michaelkohn It would be ideal to test with data that doesn't result in 100%.  Currently, all of the investigated signals in the test data also have lab samples.

**Comment by michaelkohn** [comment]
Got it. Thanks @Pall-v .  I've updated so the distribution is better for testing. There are now some signals that have been investigated but don't have lab samples.

![Screen Shot 2020-06-02 at 10 56 15 AM](https://user-images.githubusercontent.com/10096985/83541851-2f2b4200-a4c8-11ea-8319-c5a16c584e64.png)

**Comment by Pall-v** [comment]
updated chart to use `superset_signal_view`
