### ISSUE TITLE
Create the EBS "Quality" widget in Superset

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#81]
Create a chart whose

0. **Title** is "Quality"
1. **x-axis** is a timeframe, default being "day".  
2. **y-axis** is the number of signals
3. **_Reported_ Bar** (EBS03) Count of `ebsview_signal_report` that have a corresponding `ebsview_signal_verification`. X-Axis should align to the reported date of the `ebsview_signal_report`
4. **_Public Health Threat_ Bar** (EBS04) Count of `ebsview_signal_verification` reports where `threat_exists = 'yes'`. This should use the `reported` date of the corresponding signal report.
5. ~~**_% Public Health Threat_ line** (EBS05) EBS04 divided by EBS03~~  this is now #85 

More detail about the calculations can be found [here](https://docs.google.com/spreadsheets/d/1LZt789yq_1jddG0JfccFPqnXAfzirCnzIItOy7Ovaro/edit#gid=1400309261).

<img width="516" alt="Screen Shot 2020-05-20 at 12 24 06 AM" src="https://user-images.githubusercontent.com/10096985/82405343-9a3d3900-9a31-11ea-8f72-6668c9e13d55.png">

**Comment by tsengtammy** [comment]
Created two widgets (can't overlay a line plot on top of a bar plot in Superset):
1. [Reported and Public Health Threat bars ](http://superset.dev.medicmobile.org/r/9)
2. [% Public Health Threat (EBS05)](http://superset.dev.medicmobile.org/r/7)

**Comment by michaelkohn** [comment]
- [ ] Can we add an X-Axis Label: `Date Signal Reported`
- [ ] Please change the metric label from `count(*)` to `Verified`
- [ ] Please change the metric label from `count(threat_exits....` to `Threat Exists`
- [ ] From what I can tell, the X-Axis is using `ebsview_signal_verification.reported`, but it should be based off the `ebsview_signal_report.reported`. This requires joining the verification record with the signal report record (on the signal_id). 

Nothing to do for this just yet, but I think we'll want to limit the date range, ideally controlled by a dashboard-level control (ie so that you set the date range in one place and all charts honor whatever was selected). Again... we can wait until we start adding Charts to a Dashboard before we dig deeper there. 

<img width="1552" alt="Screen Shot 2020-05-28 at 3 20 35 PM" src="https://user-images.githubusercontent.com/10096985/83189581-308ef000-a0ff-11ea-8b31-f0653261a1a6.png">

**Comment by tsengtammy** [comment]
@michaelkohn It looks like it's only possible to pull from one Datasource at a time - I can't join the verification and report records in creating a Chart, we would have to materialize a view of the join beforehand. If we want to do this, I can write another SQL file to materialize a join just for this graph. (To confirm - we want `reported LEFT JOIN verification`, not inner join, right?)

The other option is to break this into two separate charts. What do you think?
