### ISSUE TITLE
Create the % Public Health Threat widget

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#85]
Creating a separate issue for this since EBS05 needed to be split into a different widget.  The original issue is #81 .

5. **_% Public Health Threat_ line** (EBS05) EBS04 divided by EBS03 

More detail about the calculations can be found [here](https://docs.google.com/spreadsheets/d/1LZt789yq_1jddG0JfccFPqnXAfzirCnzIItOy7Ovaro/edit#gid=1400309261).

<img width="516" alt="Screen Shot 2020-05-20 at 12 24 06 AM" src="https://user-images.githubusercontent.com/10096985/82405343-9a3d3900-9a31-11ea-8f72-6668c9e13d55.png">

**Comment by michaelkohn** [comment]
- [ ] Please add an X-Axis Label: `Date Signal Reported`
- [ ] Please add a Y-Axis Label: `% Percent`
- [ ] Change metric label from `CAST(COUNT(....` to `Threat Exists`
- [ ] Ideally the Y-Axis would be 0 - 100 instead of 0 - 1. 
- [ ] We should hard code the max and min for the Y-Axis to be 0 and 100.  This way the chart will always show 0-100 regardless of the maximum data series value.
- [ ] The x-axis should use the `ebsview_signal_report.reported` date

This one obviously looks a bit unruly with so much data on there, but I think once we add in the date filters (as mentioned in https://github.com/medic/config-covid/issues/81#issuecomment-635601947) it will be more manageable

<img width="1359" alt="Screen Shot 2020-05-28 at 4 02 06 PM" src="https://user-images.githubusercontent.com/10096985/83194237-553a9600-a106-11ea-854f-74b4bd352579.png">

**Comment by tsengtammy** [comment]
To follow up from #81, I think we'll have to materialize the join in a new view to make this chart work. Let me know if you'll agree!
