### ISSUE TITLE
Create EBS Dashboard

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-covid#86]
For now, please add the Charts created in https://github.com/medic/config-covid/issues/78, https://github.com/medic/config-covid/issues/81, and https://github.com/medic/config-covid/issues/85 to a new dashboard called "COVID EBS".  

We will review the color, arrangement, date filters, etc... separately.

**Comment by tsengtammy** [comment]
Dashboard here: https://superset.dev.medicmobile.org/superset/dashboard/5/
